### PR TITLE
Update for meteor 1.6.1

### PR DESCRIPTION
**Pull request by sebakerckhof**

### CODE REVIEW

**Comment by p3pp8** [comment]
Hello, is it possible to build locally this package meanwhile Urigo validates your changes? I'm trying to build it locally inside my dir packages but i get an error, meteor looks for index.js resource but the project is developed using TS, is there any dependency i have to add in order to get this working? Thanx in advance!!!

**Comment by sebakerckhof** [comment]
@p3pp8 You would need to compile the typescript

```
npm install
npm run compile
```

**Comment by sebakerckhof** [comment]
@Urigo any chance to get a look at this PR?

**Comment by p3pp8** [comment]
Thanx @sebakerckhof, i managed to build the package and got Meteor 1.6.1 up and running. I hope @Urigo will accept the PR as this is just a temporary solution, the clean thing would be to have the distributed package updated. Anyway, thank you again!!!

**Comment by Urigo** [comment]
@sebakerckhof thank you!  long time no see!
I've added you as a collaborator and as a maintainer to the package so you can merge this one and also release a new version to Atmosphere.

Also maybe it's time to bump this package to 1.0

**Comment by p3pp8** [comment]
Thanx guys! Well done!

**Pull request merged**
